fix: Iframe rehaul
appsmithorg/appsmith-docs pull request #1070
Opened 2023-03-30 04:54 UTC by harshilp24

2023-03-30 05:57 UTC, danciaclara requested changes
Add the security callout. Reword it

2023-03-30 05:57 UTC, danciaclara commented on website/docs/reference/widgets/iframe.md
> +This page explains how to use the iFrame widget to embed external content, such as apps, websites, or custom widgets, into your Appsmith application, while also providing you with the ability to comm
Include when to use the Iframe here

2023-03-30 05:57 UTC, danciaclara commented on website/docs/reference/widgets/iframe.md
> +## Display data
remove this

2023-03-30 05:57 UTC, danciaclara commented on website/docs/reference/widgets/iframe.md
we have to give an example of external app that is embedded as well

2023-03-30 05:57 UTC, danciaclara commented on website/docs/reference/widgets/iframe.md
> +| **messageMetadata**    | Any  | 	Contains metadata associated with the message received from the embedded page via the JavaScript `postMessage()` method.  |
Check the any datatype. It should be specific.

2023-03-30 07:10 UTC, danciaclara commented
We need to add a callout somewhere that says that if the external page does not allow embedding if X-Frame-Options is set to DENY

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

2023-03-31 09:08 UTC, danciaclara commented on website/docs/reference/widgets/iframe.md
> +<figure>
remove image

2023-03-31 09:09 UTC, danciaclara commented on website/docs/reference/widgets/iframe.md
> +This code listens for a message event and updates the text content of an HTML element with the ID `target` based on the data received in the event. When the message event is triggered, the `querySele
can we use the same wording here as this is too verbose and difficult to read- https://appsmith-docs-git-iframe-rehaul-get-appsmith.vercel.app/reference/appsmith-framework/widget-actions/post-message#from-appsmith-to-embedded-page

2023-03-31 09:09 UTC, danciaclara commented on website/docs/reference/widgets/iframe.md
PLease add the image from here - https://appsmith-docs-git-iframe-rehaul-get-appsmith.vercel.app/reference/appsmith-framework/widget-actions/post-message#from-appsmith-to-embedded-page

2023-03-31 09:33 UTC, harshilp24 commented on website/docs/reference/widgets/iframe.md
> +**Example**: to add a custom time picker widget to your application, you can use the `select` element for each component of the time (hour, minute, AM/PM) and a `button` to submit the selected time.
this will give lintr error

2023-03-31 17:09 UTC, danciaclara approved these changes

2023-03-31 17:09 UTC, merged