fix: 1042 kubernetes rehaul
appsmithorg/appsmith-docs pull request #1119
Opened 2023-04-11 08:09 UTC by jnikhila

2023-04-20 17:36 UTC, danciaclara requested changes

2023-04-21 04:52 UTC, jnikhila commented on website/docs/getting-started/setup/instance-management/appsmithctl.mdx
> +# Backup and Restore CLI
Import and Export are just command names which take database backups so we can still call it Back and Restore

2023-04-21 04:52 UTC, jnikhila commented on website/docs/getting-started/setup/instance-management/appsmithctl.mdx
> +## Sync backup (only for Business Edition)
This can be done as part of Appsmithctl Rehaul. I haven't looked into the content rewriting overall.

2023-04-21 04:53 UTC, jnikhila commented on website/docs/getting-started/setup/instance-configuration/README.mdx
> +| Name                                                     | Description |
Okay.

2023-04-21 04:53 UTC, jnikhila commented on website/docs/getting-started/setup/installation-guides/kubernetes/configure-high-availability.mdx
> +If you continue to face issues, contact the [support team](mailto:support@appsmith.com).
done.

2023-04-21 05:41 UTC, pratapaprasanna approved these changes

2023-04-21 10:13 UTC, pratapaprasanna requested changes
I remember changing them . Wonder how the same commands came back

2023-04-21 10:13 UTC, pratapaprasanna commented on website/docs/getting-started/setup/installation-guides/kubernetes/publish-appsmith-online.mdx
> +    helm upgrade --values values.yaml appsmith appsmith-ee/appsmith
helm upgrade -i appsmith appsmith-ee/appsmith  -f values.yaml

2023-04-21 10:13 UTC, pratapaprasanna commented on website/docs/getting-started/setup/instance-management/update-appsmith.mdx
> +     helm upgrade --values values.yaml appsmith appsmith/appsmith
helm upgrade -i appsmith appsmith/appsmith -f values.yaml

2023-04-21 10:39 UTC, pratapaprasanna approved these changes

2023-04-24 05:23 UTC, danciaclara approved these changes

2023-04-24 05:24 UTC, merged