fix: Rehaul Maintenance Window
appsmithorg/appsmith-docs pull request #1155
Opened 2023-04-20 04:38 UTC by jnikhila

- Restructuring
- Rewriting

2023-04-20 13:57 UTC, danciaclara requested changes

2023-04-20 14:01 UTC, danciaclara requested changes

2023-04-21 11:26 UTC, jnikhila commented on website/docs/getting-started/setup/instance-management/maintenance-window.md
> +# Create a Maintenance Window
Renaming this to Schedule Automatic Updates as discussed.

2023-04-21 11:27 UTC, jnikhila commented on website/docs/getting-started/setup/instance-management/maintenance-window.md
> +## Schedule a maintenance window for auto-updates
This is specific to Docker now, so further to my discussion with Sumesh have changed the header to:
Schedule automatic updates for Docker installation

2023-04-21 11:28 UTC, jnikhila commented on website/docs/getting-started/setup/instance-management/maintenance-window.md
> +3. Restart the `auto_update` container with:
I'm unsure if this is a watchtower container, as the command references the auto_update container. @sum35h - Please confirm

2023-04-24 04:40 UTC, sum35h approved these changes

2023-04-24 05:29 UTC, danciaclara approved these changes

2023-04-24 05:29 UTC, merged