fix: aws ecs ec2 rehaul
appsmithorg/appsmith-docs pull request #1197
Opened 2023-05-03 14:02 UTC by jnikhila

- Restructuring and rewriting
- Move the Update Appsmith section to [Update Appsmith](https://docs.appsmith.com/getting-started/setup/instance-management/update-appsmith) doc

2023-05-08 10:07 UTC, sum35h requested changes

2023-05-08 10:07 UTC, sum35h commented on website/docs/getting-started/setup/installation-guides/aws-ecs.md
> +  The mount directory named `/appsmith/stacks` is created on the host EC2 instance, and Appsmith data is tied to the lifecycle of the host EC2 instance in the ECS cluster.
@jnikhila  Can we make this stand out, like an alert?

2023-05-08 11:14 UTC, sum35h submitted a review, later dismissed

2023-05-09 07:16 UTC, danciaclara approved these changes

2023-05-09 07:23 UTC, danciaclara approved these changes

2023-05-09 07:23 UTC, merged