683 : Adding documentation changes
appsmithorg/appsmith-docs pull request #12
Opened 2020-10-02 06:04 UTC by Saket2

2020-10-02 07:05 UTC, Nikhil-Nandagopal commented on core-concepts/building-the-ui/README.md
> +**Widget properties don't have to be static!** To make it dynamic, type **`{{ }}`** inside the widget property and bind it to an API name or Widget name. You can learn more about working with widgets
@Saket2 can you update "bind it to an API/Query/Widget"

2020-10-02 07:06 UTC, Nikhil-Nandagopal commented on core-concepts/building-the-ui/README.md
> +Widget properties can be edited via the property pane which could be opened using top-right icon (Edit Widget Properties). Widget properties can affect the widget data, styling and actions.
instead of could, let's use "is"

2020-10-02 07:06 UTC, Nikhil-Nandagopal requested changes
@Saket2 had a few ideas here, the rest looks good

2020-10-02 08:26 UTC, Saket2 commented
@Nikhil-Nandagopal Made the suggested changes.

2020-10-05 07:02 UTC, Nikhil-Nandagopal approved these changes

2020-10-05 07:02 UTC, merged