feat: Multiple Environments
appsmithorg/appsmith-docs pull request #1449
Opened 2023-07-07 04:16 UTC by harshilp24

## Checklist
I have:
- [ ] run the content through Grammarly
- [ ] linked to sample apps when relevant
- [ ] added the meta description for each page in the PR
- [ ] minimized the callouts and added only when necessary
- [ ] added the `queryString` parameter to the Tabs (if used)
- [ ] masked PII in images. For example, login credentials, account details, and more
- [ ] added images only when necessary
- [ ] deleted the images that are no longer used for the updated pages in the PR
- [ ] followed the image file naming convention while renaming or adding new images. (Use lowercase letters, dashes between words, and be as descriptive as possible)
- [ ] used the `<figure/>` tag instead of a markdown representation for images
- [ ] added the `<figcaption/>` tag to add a caption to the image
- [ ] added the `alt` attribute in the `<img/>` tag
- [ ] verified and updated the cross-references or created redirect rules for the changed or removed content 
- [ ] reviewed and applied the style changes for UI formatting. For example, Bold the UI elements(Buttons on screen) used in the doc.

2023-07-11 04:23 UTC, danciaclara requested changes
Some of these comments were also mentioned over the review call but they don't seem to have been taken into consideration.

2023-07-19 04:59 UTC, sribalajig commented on website/docs/connect-data/concepts/Multiple-Environments.md
> +Multiple environments allows you to separate staging and production configurations of a datasource. Each environment mimics the necessary conditions required for a particular phase, ensuring a contro
We need to modify this paragraph. I feel there is some jargon here that is not easy to understand, especially this line 

> Each environment mimics the necessary conditions required for a particular phase, ensuring a controlled and isolated environment for specific tasks.

Meaning is not clear.

2023-07-19 05:03 UTC, sribalajig commented on website/docs/connect-data/concepts/Multiple-Environments.md
> +# Multiple Environments
Suggestion : Let's call this "Datasource Environments"

2023-07-19 05:07 UTC, sribalajig commented on website/docs/connect-data/concepts/Multiple-Environments.md
> +This page describes Multiple environments, which allows developers to isolate development and testing from production, avoiding unintended modifications and facilitating seamless switching between da
This page describes ~~Multiple~~ Datasource environments

2023-07-19 05:10 UTC, sribalajig commented on website/docs/connect-data/concepts/Multiple-Environments.md
> +This page describes Multiple environments, which allows developers to isolate development and testing from production, avoiding unintended modifications and facilitating seamless switching between da
> which allows developers to isolate development and testing from production, avoiding unintended modifications and facilitating seamless switching between datasources.
which allows developers to isolate their development and testing datasources from their production datasources. By enabling this isolation, developers can protect their production data from unintended modifications. It also provides them the ability to switch seamlessly between staging and production datasources.

2023-07-19 05:14 UTC, sribalajig commented on website/docs/connect-data/concepts/Multiple-Environments.md
> +* **Isolation and Risk Management:** Multiple environments allow developers to separate testing, and production environments, reducing the risk of unintended modifications and providing a controlled
each stage of **the software development cycle**

2023-07-19 05:16 UTC, sribalajig commented on website/docs/connect-data/concepts/Multiple-Environments.md
> +When working with multiple environments in Appsmith, it is important to note that custom environments are not currently supported. Appsmith provides predefined staging and production environments, bu
Please change "multiple environments" to "datasource environments".

2023-07-19 05:17 UTC, sribalajig commented on website/docs/connect-data/concepts/Multiple-Environments.md
> +When working with multiple environments in Appsmith, it is important to note that custom environments are not currently supported. Appsmith provides predefined staging and production environments, bu
Need to define what "custom environments" means. I think this is a term we use internally and it will not be readily understood by users.

2023-07-19 05:18 UTC, sribalajig commented on website/docs/connect-data/how-to-guides/setup-multiple-environments.md
> +SaaS integrations such as Google Sheets, HubSpot, Twilio, and Airtable do not support multiple environments.
datasource environments

2023-07-27 06:05 UTC, danciaclara submitted a review, later dismissed

2023-07-31 05:31 UTC, sribalajig submitted a review, later dismissed

2023-07-31 05:36 UTC, danciaclara submitted a review, later dismissed

2023-08-01 05:33 UTC, danciaclara approved these changes

2023-08-01 05:33 UTC, merged