fix: Added BigQuery integration to data integrations
appsmithorg/appsmith-docs pull request #1483
Opened 2023-07-19 00:01 UTC by spark-c

added card for Google BigQuery to our Connect Data > Third-Party Integrations page.

Resolves #1398 

## Checklist
I have:
- [x] run the content through Grammarly
- [x] linked to sample apps when relevant
- [x] added the meta description for each page in the PR
- [x] minimized the callouts and added only when necessary
- [x] added the `queryString` parameter to the Tabs (if used)
- [x] masked PII in images. For example, login credentials, account details, and more
- [x] added images only when necessary
- [x] deleted the images that are no longer used for the updated pages in the PR
- [x] followed the image file naming convention while renaming or adding new images. (Use lowercase letters, dashes between words, and be as descriptive as possible)
- [x] used the `<figure/>` tag instead of a markdown representation for images
- [x] added the `<figcaption/>` tag to add a caption to the image
- [x] added the `alt` attribute in the `<img/>` tag
- [x] verified and updated the cross-references or created redirect rules for the changed or removed content 
- [x] reviewed and applied the style changes for UI formatting. For example, Bold the UI elements(Buttons on screen) used in the doc.

2023-07-19 06:43 UTC, jnikhila requested changes

2023-07-19 06:43 UTC, jnikhila commented on website/docs/connect-data/integrations.md
> +    <div class="columnGrid column-two" style={{padding:"20px"}}>
The formatting is broken for Zapier.
<img width="622" alt="Screenshot 2023-07-19 at 12 12 06 PM" src="https://github.com/appsmithorg/appsmith-docs/assets/99252011/11a232ee-4d6b-4a08-a56d-8cce4e890ad9">

2023-07-27 12:34 UTC, danciaclara approved these changes

2023-07-27 12:44 UTC, danciaclara approved these changes

2023-07-27 12:45 UTC, jnikhila approved these changes

2023-07-27 12:46 UTC, closed without merging

2023-07-27 12:47 UTC, danciaclara commented
@spark-c Can you create a new pull request for this? There are multiple changes in this PR that are unrelated to the issue.