feat: User provisioning & Group sync
appsmithorg/appsmith-docs pull request #1519
Opened 2023-07-26 11:55 UTC by Pranay105

## Checklist
I have:
- [ ] run the content through Grammarly
- [ ] linked to sample apps when relevant
- [ ] added the meta description for each page in the PR
- [ ] minimized the callouts and added only when necessary
- [ ] added the `queryString` parameter to the Tabs (if used)
- [ ] masked PII in images. For example, login credentials, account details, and more
- [ ] added images only when necessary
- [ ] deleted the images that are no longer used for the updated pages in the PR
- [ ] followed the image file naming convention while renaming or adding new images. (Use lowercase letters, dashes between words, and be as descriptive as possible)
- [ ] used the `<figure/>` tag instead of a markdown representation for images
- [ ] added the `<figcaption/>` tag to add a caption to the image
- [ ] added the `alt` attribute in the `<img/>` tag
- [ ] verified and updated the cross-references or created redirect rules for the changed or removed content 
- [ ] reviewed and applied the style changes for UI formatting. For example, Bold the UI elements(Buttons on screen) used in the doc.

2023-08-02 11:19 UTC, danciaclara requested changes
In both AD and Okta at the bottom, you need to add

## See Also
- Setup SCIM provisioning


also are not adding any screenshots for both AD and Okta to help users to align in case there are many back and forth steps happening.

2023-08-02 11:19 UTC, danciaclara commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +This page shows how to set up SCIM on your Appsmith instance to streamline the user lifecycle management based on your SSO provider.
```suggestion
This page shows how to configure Appsmith for SCIM to enable the automatic provisioning of users and groups based on your SSO provider.
```

2023-08-02 11:19 UTC, danciaclara commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +- A SAML SSO provider configured on your Appsmith instance.
```suggestion
- A SAML SSO provider configured on your Appsmith instance. See [SAML SSO](/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml) for instructions.
```

2023-08-02 11:19 UTC, danciaclara commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +
add screenshot on the setup page on Appsmith

2023-08-02 11:36 UTC, Pranay105 commented
> In both AD and Okta at the bottom, you need to add
> 
> ## See Also
> * Setup SCIM provisioning
> 
> also are we not adding any screenshots for both AD and Okta to help users to align in case there are many back and forth steps happening?

I did not feel the need for screenshots as such. During Attribute Mapping steps, there is a possibility of a little confusion, but I still feel the instructions are enough.

2023-08-02 11:54 UTC, danciaclara requested changes

2023-08-02 11:54 UTC, danciaclara commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +<TabItem label="Active Direcotry (SAML)" value="scim-ad-saml">
```suggestion
<TabItem label="Active Directory (SAML)" value="scim-ad-saml">
```

2023-08-02 11:54 UTC, danciaclara commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +<TabItem label="Active Direcotry (SAML)" value="scim-ad-saml">
I think its misspelt in other places also

2023-08-02 11:54 UTC, danciaclara commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +
This section needs to have a separate heading

**Assign users and groups to the application**

2023-08-02 11:54 UTC, danciaclara commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +
```suggestion
### Add SCIM provisioning
```

2023-08-02 11:54 UTC, danciaclara commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +3. Go to the **Provisioning** tab, click **Edit** on SCIM connection.
Above this add, 

### Choose provisioning options

2023-08-02 11:54 UTC, danciaclara commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +
```suggestion
### Configure the enterprise application
```

2023-08-02 13:01 UTC, danciaclara submitted a review, later dismissed

2023-08-02 13:02 UTC, danciaclara reviewed
Hey I'll approve it once Akhil completes tech review

2023-08-03 10:49 UTC, Pranay105 commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +    - **Switch([IsSoftDeleted], , "False", "True", "True", "False")**
Ignore the Linter error for this. This is a UI element in AD that needs to be mentioned as it is in the product

2023-08-04 12:21 UTC, infinitetrooper submitted a review, later dismissed

2023-08-04 12:24 UTC, infinitetrooper commented on website/docs/advanced-concepts/user-provisioning-group-sync.mdx
> +## Configure Identity provider
I in Identity should be lowercase right?

2023-08-04 12:41 UTC, danciaclara approved these changes

2023-08-04 12:42 UTC, merged