FEATURE-1726 : Iframe Widget
appsmithorg/appsmith-docs pull request #159
Opened 2021-06-11 15:42 UTC by wmdev0808

## Documentation Link 

https://docs.appsmith.com/widget-reference/iframe

## Describe the problem

- Add the corresponding documentation for iframe widget

2021-06-12 05:30 UTC, somangshu requested changes

2021-06-12 05:30 UTC, somangshu commented on widget-reference/iframe.md
> +| **onMessageReceived** | Sets the action to be run when a message event is received from the embedded page. |
This should be `Sets the action to be run when a postMessage event is received from the embedded page`

2021-06-14 14:29 UTC, somangshu commented on widget-reference/iframe.md
> +| **onMessageReceived** | Sets the action to be run when a message event is received from the embedded page. |
@wmdev0808 please check the above!

2021-06-15 05:06 UTC, somangshu approved these changes

2021-07-04 17:32 UTC, vihar approved these changes

2021-07-04 17:32 UTC, merged