FEATURE-3261 : Menu Widget
appsmithorg/appsmith-docs pull request #166
Opened 2021-07-01 15:38 UTC by wmdev0808

-- add documentation for menu widget

2021-07-02 05:13 UTC, somangshu requested changes

2021-07-02 05:13 UTC, somangshu commented on SUMMARY.md
> +* [Menu](widget-reference/menu.md)
menu-button

2021-07-02 05:13 UTC, somangshu commented on widget-reference/menu.md
> +  Menus are used to represent a set of actions in a group.
Menu buttons*

2021-07-02 05:13 UTC, somangshu commented on widget-reference/menu.md
> +| **menuItems** | Array of menu items in the dropdown list. Every menu item has the same properties as the top-level properties. |
We need to add documentation for the menuItem settings as well.

2021-07-02 09:48 UTC, somangshu approved these changes
LGTM.

@vihar please check

2021-07-07 04:01 UTC, vihar commented
We'll need to add GIF's here, can I have the link to deploy-preview?

2021-07-07 05:42 UTC, somangshu commented
@vihar [here](https://github.com/appsmithorg/appsmith/pull/5334) is the menu button widget PR. Let me know if you need anything else

2021-07-26 05:41 UTC, merged