included use cases to the download action documentation
appsmithorg/appsmith-docs pull request #177
Opened 2021-08-03 09:00 UTC by ohansFavour

Added use cases and caveats for the download action documentation.

2021-08-03 09:53 UTC, hetunandu requested changes
Small change

2021-08-03 09:53 UTC, hetunandu commented on framework-reference/download.md
> +| **data**          | Data that would be downloaded              |
data or url

2021-08-03 10:38 UTC, ohansFavour commented on framework-reference/download.md
> +| **data**          | Data that would be downloaded              |
All right. Fixed in latest commit.

2021-08-03 10:38 UTC, hetunandu approved these changes

2021-08-16 05:47 UTC, vihar commented
@ohansFavour, can you delete `.DS_Store` files on this commit?

2021-08-16 05:56 UTC, ohansFavour commented
> @ohansFavour, can you delete `.DS_Store` files on this commit?

Sure

2021-08-19 06:58 UTC, merged