fix: Guide for fetch and filter GSheet data
appsmithorg/appsmith-docs pull request #1818
Opened 2023-10-17 11:22 UTC by rashmi-sahoo-git

closes #1816 
## Checklist
I have:
- [ ] run the content through Grammarly
- [ ] linked to sample apps when relevant
- [ ] added the meta description for each page in the PR
- [ ] minimized the callouts and added only when necessary
- [ ] added the `queryString` parameter to the Tabs (if used)
- [ ] masked PII in images. For example, login credentials, account details, and more
- [ ] added images only when necessary
- [ ] deleted the images that are no longer used for the updated pages in the PR
- [ ] followed the image file naming convention while renaming or adding new images. (Use lowercase letters, dashes between words, and be as descriptive as possible)
- [ ] used the `<figure/>` tag instead of a markdown representation for images
- [ ] added the `<figcaption/>` tag to add a caption to the image
- [ ] added the `alt` attribute in the `<img/>` tag
- [ ] verified and updated the cross-references or created redirect rules for the changed or removed content 
- [ ] reviewed and applied the style changes for UI formatting. For example, Bold the UI elements(Buttons on screen) used in the doc.

2023-10-19 13:57 UTC, sneha122 commented
@rashmi-sahoo-git Here are couple of feedback points, let me know what you think:
- Can we make it clear in the document, that when you create a new gsheet query, filter format will appear only after we select spreadsheet and sheet, because as a new user if I am following this document, initially filter format will be hidden and will only be seen once you select operation, spreadsheet and sheet. This will set the correct context and there wont be confusion for the user
- Same for cell range, we need to set the context before we start with the guide i.e. we need to select spreadsheet, sheet etc before filter options are shown
- Is it possible to add a small image of google sheet rows and columns to show the row number and column letter syntax? This is a very nit pick kind of thing, but I think would be very useful for someone who does not know much about it
- Cell_range_row and Cell_range_col are these default variables provided by appsmith to access cell range? or do we need to define it somewhere? If we need to define it and use, can we have a link to how we can define these and use it? Because for new user the concept of binding may be new and they might end up getting stuck at this phase
- What pagination offset does is not very clear from the documentation, can we please explain it in a better way if possible?

2023-10-20 12:08 UTC, danciaclara requested changes

2023-10-20 12:08 UTC, danciaclara commented on website/docs/connect-data/how-to-guides/filter-data-google-sheet.md
> +### Filter data using where clause
```suggestion
### Using where clause
```

2023-10-20 12:08 UTC, danciaclara commented on website/docs/connect-data/how-to-guides/filter-data-google-sheet.md
> +### Filter data using a cell range
```suggestion
### Using a cell range
```

2023-10-20 12:08 UTC, danciaclara commented on website/docs/connect-data/how-to-guides/filter-data-google-sheet.md
> +### Pagination
```suggestion
### Server-side Pagination
```

2023-10-20 12:31 UTC, danciaclara approved these changes

2023-10-20 12:32 UTC, merged