fix: Default branch fixes
appsmithorg/appsmith-docs pull request #1884
Opened 2023-11-21 09:10 UTC by harshilp24

## Checklist
I have:
- [ ] run the content through Grammarly
- [ ] linked to sample apps when relevant
- [ ] added the meta description for each page in the PR
- [ ] minimized the callouts and added only when necessary
- [ ] added the `queryString` parameter to the Tabs (if used)
- [ ] masked PII in images. For example, login credentials, account details, and more
- [ ] added images only when necessary
- [ ] deleted the images that are no longer used for the updated pages in the PR
- [ ] followed the image file naming convention while renaming or adding new images. (Use lowercase letters, dashes between words, and be as descriptive as possible)
- [ ] used the `<figure/>` tag instead of a markdown representation for images
- [ ] added the `<figcaption/>` tag to add a caption to the image
- [ ] added the `alt` attribute in the `<img/>` tag
- [ ] verified and updated the cross-references or created redirect rules for the changed or removed content 
- [ ] reviewed and applied the style changes for UI formatting. For example, Bold the UI elements(Buttons on screen) used in the doc.

2023-11-21 10:56 UTC, infinitetrooper requested changes

2023-11-23 07:53 UTC, infinitetrooper submitted a review, later dismissed

2023-11-24 02:50 UTC, danciaclara requested changes

2023-11-24 02:50 UTC, danciaclara commented on website/docs/advanced-concepts/version-control-with-git/environments-with-git.md
>  If you are an enterprise user, you can choose a different branch as the default, offering customization based on specific project requirements or preferences. Learn more about [Default branch](/advan
```suggestion
If you are an enterprise user, you can set a [Default branch](/advanced-concepts/version-control-with-git/working-with-branches#default-branch) and [Branch protection](/advanced-concepts/version-control-with-git/working-with-branches#branch-protection), ensuring code quality, collaboration, and stability in a collaborative development environment. 
```

2023-11-24 02:50 UTC, danciaclara commented on website/docs/advanced-concepts/version-control-with-git/environments-with-git.md
> +Additionally, you can add multiple branches to branch protection for additional security measures. Learn more about [Branch protection](/advanced-concepts/version-control-with-git/working-with-branch
```suggestion

```

2023-11-24 02:54 UTC, danciaclara approved these changes

2023-11-24 02:54 UTC, merged