fix: Added details for triple braces to query parameters
appsmithorg/appsmith-docs pull request #1893
Opened 2023-11-23 11:07 UTC by rashmi-sahoo-git

closes #949 
## Checklist
I have:
- [ ] run the content through Grammarly
- [ ] linked to sample apps when relevant
- [ ] added the meta description for each page in the PR
- [ ] minimized the callouts and added only when necessary
- [ ] added the `queryString` parameter to the Tabs (if used)
- [ ] masked PII in images. For example, login credentials, account details, and more
- [ ] added images only when necessary
- [ ] deleted the images that are no longer used for the updated pages in the PR
- [ ] followed the image file naming convention while renaming or adding new images. (Use lowercase letters, dashes between words, and be as descriptive as possible)
- [ ] used the `<figure/>` tag instead of a markdown representation for images
- [ ] added the `<figcaption/>` tag to add a caption to the image
- [ ] added the `alt` attribute in the `<img/>` tag
- [ ] verified and updated the cross-references or created redirect rules for the changed or removed content 
- [ ] reviewed and applied the style changes for UI formatting. For example, Bold the UI elements(Buttons on screen) used in the doc.

2023-11-23 11:10 UTC, rashmi-sahoo-git commented
@bharath31 Please review if this looks good.

2023-11-24 05:41 UTC, bharath31 requested changes

2023-11-24 05:41 UTC, bharath31 commented on website/docs/reference/appsmith-framework/widget-actions/navigate-to.md
> +Query parameters passed via the URL. Used to share information with the destination page. It is important to use triple braces ({{{ }}}) to ensure that the parameters are encoded correctly as a part
I don't think "triple braces" is a known concept and this is also not something we would want to to introduce to our users. Syntactically, this is just a combination of two different concepts:
1. A JS binding: `{{ }}`
2. An object: `{"key": "value"}`

2023-11-28 08:34 UTC, danciaclara requested changes

2023-11-28 08:34 UTC, danciaclara commented on website/docs/reference/appsmith-framework/widget-actions/navigate-to.md
> +{{{ "key": "value" }}}
```suggestion
{{
{ "key": "value" }
}}
```

2023-11-28 08:34 UTC, danciaclara approved these changes

2023-11-28 10:29 UTC, bharath31 approved these changes

2023-11-28 10:32 UTC, merged