feat: Custom widget
appsmithorg/appsmith-docs pull request #2050
Opened 2024-01-09 09:00 UTC by harshilp24

## Checklist
I have:
- [ ] run the content through Grammarly
- [ ] linked to sample apps when relevant
- [ ] added the meta description for each page in the PR
- [ ] minimized the callouts and added only when necessary
- [ ] added the `queryString` parameter to the Tabs (if used)
- [ ] masked PII in images. For example, login credentials, account details, and more
- [ ] added images only when necessary
- [ ] deleted the images that are no longer used for the updated pages in the PR
- [ ] followed the image file naming convention while renaming or adding new images. (Use lowercase letters, dashes between words, and be as descriptive as possible)
- [ ] used the `<figure/>` tag instead of a markdown representation for images
- [ ] added the `<figcaption/>` tag to add a caption to the image
- [ ] added the `alt` attribute in the `<img/>` tag
- [ ] verified and updated the cross-references or created redirect rules for the changed or removed content 
- [ ] reviewed and applied the style changes for UI formatting. For example, Bold the UI elements(Buttons on screen) used in the doc.

2024-01-16 11:56 UTC, danciaclara requested changes

2024-01-16 11:56 UTC, danciaclara commented on website/docs/build-apps/how-to-guides/custom-widget.md
> +
can we make the slug more relatable?  custom-widget-vanillajs

2024-01-16 11:56 UTC, danciaclara commented on website/sidebars.js
> +            'build-apps/how-to-guides/custom-widget',
remove it from sidebar for now. we will only publish this after we have reviewed it thoroughly.

2024-01-16 12:02 UTC, danciaclara submitted a review, later dismissed

2024-01-19 09:38 UTC, sbalaji1192 approved these changes

2024-01-19 11:53 UTC, danciaclara approved these changes

2024-01-19 11:53 UTC, merged