feat: workflow tutorial
appsmithorg/appsmith-docs pull request #2082
Opened 2024-01-26 08:47 UTC by jnikhila

## Description 

Provide a concise summary of the changes made in this pull request.

- 

## Type of PR

Check the appropriate box:

- [ ] Review Fixes
- [ ] Documentation Overhaul
- [ ] Feature/Story
    - Link one or more Engineering Tickets

        * 

- [ ] A-Force
- [ ] Error in documentation

## Documentation tickets
 Link to one or more documentation tickets:
 
 - 

## Checklist
Choose only the ones that are applicable.

- [ ] Checked for Grammarly suggestions.
- [ ] Adhered to the writing checklist.
- [ ] Adhered the media checklist.
- [ ] Verified and updated cross-references or added redirect rules.
- [ ] Tested the redirect rules on deploy preview.
- [ ] Validated the modifications made to the content on deploy preview.
- [ ] Validated the CSS modifications on different screen sizes.

2024-02-02 06:36 UTC, danciaclara requested changes

2024-02-02 07:57 UTC, jnikhila commented on website/docs/workflows/tutorials/set-up-webhook-workflow.md
> +1. Click the **Create New** button in your workspace, and from the available options, choose **New Workflow**. This action creates a new workflow in your workspace and takes you to the **Main** JS ob
I'll rewrite this.

2024-02-02 07:58 UTC, jnikhila commented on website/docs/workflows/tutorials/set-up-webhook-workflow.md
> +6. Copy and save the **URL** and the **Bearer Token**.
I'll check this.

2024-02-08 12:32 UTC, danciaclara requested changes

2024-02-21 06:20 UTC, jnikhila commented on website/docs/workflows/reference/workflow-functions.md
> +assignRequest({
@infinitetrooper and @srix - what will be the return type for this?

2024-02-28 14:42 UTC, jnikhila commented on website/docs/advanced-concepts/granular-access-control/roles.md
> +| **Workflows** | Create new workflows and resources inside a workflow. | Required to make changes to the Workflow.| Required to delete a workflow. Users will need **Edit** permission to delete indiv
@infinitetrooper - Could you please confirm about the permissions for Publishing workflows?

2024-03-07 11:33 UTC, infinitetrooper requested changes

2024-03-08 05:02 UTC, jnikhila commented on website/docs/workflows/reference/workflow-functions.md
> +## assignRequest()
Here we are just talking about the function. So the title will be `assignRequest`. I can add in the description that it is available to be accessed using `appsmith.worfklow` global object available in workflows.

2024-03-08 05:10 UTC, jnikhila commented on website/docs/workflows/reference/workflow-functions.md
> +The `assignRequest()` function creates a pending request that requires user intervention and can be accessed later in your apps to enable users to take action.
Rewritten this part to capture the necessary details.

2024-03-08 05:16 UTC, jnikhila commented on website/docs/workflows/reference/workflow-functions.md
> +   Specifies the user or users to whom the request will be assigned for resolution. Each element in the array has to be the email that you use for logging into your Appsmith app. It's mandatory to su
It is mentioned that each element should be an email. However, have rewritten it.

2024-03-08 05:18 UTC, jnikhila commented on website/docs/workflows/reference/workflow-functions.md
> +
what will be the impact of that when the workflow is unpaused?

2024-03-08 05:24 UTC, jnikhila commented on website/docs/advanced-concepts/granular-access-control/roles.md
> +| **Workflows** | Create new workflows and resources inside a workflow. | Required to make changes to the Workflow.| Required to delete a workflow. Users will need **Edit** permission to delete indiv
@infinitetrooper - did you get a chance to look into this? Please share what's missing here.

2024-03-11 10:27 UTC, jnikhila commented on website/docs/workflows/tutorials/create-webhook-workflow.md
> + <h1> Create Webhook Workflow</h1>
This is updated to `Create Basic Workflow.`

2024-03-11 12:10 UTC, merged