fix: Video Widget URL Property Changes
appsmithorg/appsmith-docs pull request #2097
Opened 2024-02-05 17:09 UTC by harshilp24

## Description 

Provide a concise summary of the changes made in this pull request.

- 

## Type of PR

Check the appropriate box:

- [ ] Review Fixes
- [ ] Documentation Overhaul
- [ ] Feature/Story
    - Link one or more Engineering Tickets

        * 

- [ ] A-Force
- [ ] Error in documentation

## Documentation tickets
 Link to one or more documentation tickets:
 
 - 

## Checklist
Choose only the ones that are applicable.

- [ ] Checked for Grammarly suggestions.
- [ ] Adhered to the writing checklist.
- [ ] Adhered the media checklist.
- [ ] Verified and updated cross-references or added redirect rules.
- [ ] Tested the redirect rules on deploy preview.
- [ ] Validated the modifications made to the content on deploy preview.
- [ ] Validated the CSS modifications on different screen sizes.

2024-02-05 17:39 UTC, somangshu commented on website/docs/reference/widgets/video.md
Let's simplify to say that it now supports IP based URL. Let's also tag examples for the same

2024-02-08 05:53 UTC, danciaclara requested changes

2024-02-08 05:53 UTC, danciaclara commented on website/docs/reference/widgets/video.md
> +* **IP Based:** 127.0.0.10:8080/path/to/video.mp4
```suggestion
* **IP Based:** `127.0.0.10:8080/path/to/video.mp4`
```

2024-02-08 05:53 UTC, danciaclara commented on website/docs/reference/widgets/video.md
> +* **URL Based:** https://assets.appsmith.com/widgets/bird.mp4
```suggestion
* **URL Based:** `https://assets.appsmith.com/widgets/bird.mp4`
```

2024-02-08 06:06 UTC, merged