Part1  doc improvement
appsmithorg/appsmith-docs pull request #27
Opened 2020-10-03 07:22 UTC by Hard-Coder05

Fixes: Issue #648 (https://github.com/appsmithorg/appsmith/issues/648) 
All the changes mentioned are completed!

2020-10-03 07:23 UTC, Hard-Coder05 commented
@Nikhil-Nandagopal @mohanarpit I have raise th PR please review it once!

2020-10-04 05:58 UTC, Nikhil-Nandagopal commented on faq.md
>  Appsmith isn't built for complicated UI interactions that are common to e-commerce or other consumer-facing websites. It works great for tools internal to your team or organization but you wouldn't g
This seems incorrect

2020-10-04 05:58 UTC, Nikhil-Nandagopal commented on faq.md
> +## Like with every GOD particle, Appsmith also has its own limitations?
Let's not make this change

2020-10-04 05:59 UTC, Nikhil-Nandagopal commented on quick-start.md
> +description: Appsmith stands for speed and getting started with Appsmith is just as fast as Usain Bolt.
Please skip this change

2020-10-04 06:00 UTC, Nikhil-Nandagopal commented on faq.md
> +Yes, absolutely. You can write JS code anywhere inside the product within `{{ }}`. We know how complex and intricate business logic can be and trying to build it without code can get excruciating.  A
This change is incorrect

2020-10-04 06:00 UTC, Nikhil-Nandagopal commented on faq.md
> +## What kind of apps can be built on Appssmith?
Appsmith is misspelled

2020-10-04 06:01 UTC, Nikhil-Nandagopal requested changes
@Hard-Coder05 i've requested a few changes. Also please run this through grammarly

2020-10-04 06:21 UTC, Hard-Coder05 commented
@Nikhil-Nandagopal I have made the required changes.

2020-10-04 06:50 UTC, Nikhil-Nandagopal approved these changes

2020-10-04 06:51 UTC, merged

2020-11-04 15:45 UTC, Hard-Coder05 commented
@Nikhil-Nandagopal what about the hacktoberfest swags?...

2020-11-05 06:13 UTC, areyabhishek commented
@Hard-Coder05 Thanks for contributing! Could you fill out your information in this form? https://airtable.com/shrZNbhUJyoVkYVws We'll be shipping swag in a couple of weeks.