Fix navigateTo description
appsmithorg/appsmith-docs pull request #306
Opened 2021-12-20 22:12 UTC by kasarchou

Fixes appsmithorg/appsmith#9564

2021-12-20 22:16 UTC, kasarchou commented
Fixes appsmithorg/appsmithorg#9564

2022-01-04 17:59 UTC, Pranay105 requested changes
Great work @kasarchou . I just suggested some structural changes, Please have a look.

2022-01-04 17:59 UTC, Pranay105 commented on framework-reference/navigateto.md
>    With navigateTo, we can navigate in between the internal pages of Appsmith. It
navigateTo allows the user to navigate between the internal pages of the App or to an external URL.

2022-01-04 17:59 UTC, Pranay105 commented on framework-reference/navigateto.md
> +  external webpage. Then assign it to navigateTo to be redirected to it when the
Enter the page name or the external URL in the navigateTo function (under a triggerable action like onClick), enter the Query parameters if required, and select the destination for the new page (a new window or same window.)

2022-01-08 20:15 UTC, kasarchou commented
I committed the changes you requested. You are right that explains the method far better. Thank you for your help @Pranay105 .
Although i hope i committed it  correctly, if not please let me know.

2022-01-12 06:29 UTC, Pranay105 approved these changes

2022-01-12 06:30 UTC, merged

2022-03-14 22:10 UTC, Rishabhkaul commented
@Pranay105 The changes you had proposed don't seem to be reflecting. The intro paragraph still ends with a random sentence "Enter t"
![Screenshot 2022-03-14 at 3 10 03 PM](https://user-images.githubusercontent.com/1650391/158269366-547f293e-b92b-4209-b960-e64b8df50051.png)

2022-03-15 06:59 UTC, Pranay105 commented
This happened because the text came under the page name description. I think one can add limited text here. It should come below. @Rishabhkaul, I'll fix it.