#858 gif for table widget
appsmithorg/appsmith-docs pull request #32
Opened 2020-10-03 16:55 UTC by gogetter22

2020-10-04 06:35 UTC, Nikhil-Nandagopal commented on widget-reference/table.md
>  | **onRowSelected** | Sets the action to be run when user selects a row in the table. Default supported actions are: Call API, Execute DB Query, Navigate to Page, Show Alert, Open / Close popup |
@gogetter22 can you update the gif to drop the table, resize it so it's more visible, and bind it to a query.

2020-10-04 06:35 UTC, Nikhil-Nandagopal requested changes
@gogetter22 requested changes

2020-10-04 08:10 UTC, gogetter22 commented
@Nikhil-Nandagopal : Made the changes, please review.

2020-10-05 11:45 UTC, Nikhil-Nandagopal commented on widget-reference/table.md
>  | **onRowSelected** | Sets the action to be run when user selects a row in the table. Default supported actions are: Call API, Execute DB Query, Navigate to Page, Show Alert, Open / Close popup |
@gogetter22 something seems wrong with the table in the gif, the bg is transparent instead of white. How did this happen?

2020-10-05 11:47 UTC, Nikhil-Nandagopal requested changes
- The Table in the Gif is looking strange
- The table is calling Queries instead of displaying data from a query
- Create a `select * from users` query and run it, bind the query to the table data property as {{ query.data}}

2020-10-05 17:44 UTC, closed without merging