fix: add new file for query errors
appsmithorg/appsmith-docs pull request #554
Opened 2022-11-09 12:47 UTC by jnikhila

Add troubleshooting for the 'Response error larger than 5MB':
- Added a new troubleshooting page to capture Query errors
- Added screenshots
- Added a sidebar link for displaying it in the sidebar menu

2022-11-10 12:34 UTC, spark-c requested changes

2022-11-10 12:34 UTC, spark-c commented on website/docs/help-and-support/troubleshooting-guide/query-errors.md
> +You may see below errors when working with [API](/core-concepts/connecting-to-data-sources/authentication/connect-to-apis) or [Query](/core-concepts/data-access-and-binding/querying-a-database/) resp
Small suggestion for grammar:

> You may see the below errors when working with [API](/core-concepts/connecting-to-data-sources/authentication/connect-to-apis) or [Query](/core-concepts/data-access-and-binding/querying-a-database/) responses.

2022-11-10 12:34 UTC, spark-c commented on website/docs/help-and-support/troubleshooting-guide/query-errors.md
> +You may see below errors when working with [API](/core-concepts/connecting-to-data-sources/authentication/connect-to-apis) or [Query](/core-concepts/data-access-and-binding/querying-a-database/) resp
(Otherwise looks good!)

2022-11-11 09:01 UTC, spark-c approved these changes

2022-11-17 05:21 UTC, pranavkanade approved these changes
Looks good to me 👍

2022-11-18 06:58 UTC, merged