Added docs for controlling widget visibility
appsmithorg/appsmith-docs pull request #56
Opened 2020-10-22 06:42 UTC by Rithvik-Reddy

The commit adds an extra page to docs to show users how to control the visibility of widgets dynamically.

2020-10-23 05:53 UTC, Nikhil-Nandagopal requested changes
@Rithvik-Reddy I've added my comments

2020-10-26 08:47 UTC, Rithvik-Reddy commented on core-concepts/building-the-ui/widget-visibility.md
> +  The visibility of widgets can be controlled dynamically through another widget or through an API.
Alright

2020-10-26 08:49 UTC, Rithvik-Reddy commented on core-concepts/building-the-ui/widget-visibility.md
> +```text
The GIF that I added shows how to control the visibility of a widget from another widget dynamically. Do you want me to add the an example of the dyanmic forms?

2020-10-27 04:00 UTC, Rithvik-Reddy commented
@Nikhil-Nandagopal I commented a few questions, please let me know before I make changes.

2020-10-27 08:47 UTC, Nikhil-Nandagopal commented on core-concepts/building-the-ui/widget-visibility.md
> +```text
@Rithvik-Reddy yes as an additional example, show a dynamic form using a tab widget to hide / show different flows

2020-10-27 10:17 UTC, Rithvik-Reddy commented on core-concepts/building-the-ui/widget-visibility.md
> +```text
Alright

2020-10-28 19:02 UTC, Rithvik-Reddy commented
Hi @Nikhil-Nandagopal, Ive committed the requested changes.

2020-10-31 06:07 UTC, Nikhil-Nandagopal approved these changes

2020-10-31 06:08 UTC, merged

2020-10-31 06:08 UTC, Nikhil-Nandagopal commented
@Rithvik-Reddy Thank you for the contribution 🎉