context-object
appsmithorg/appsmith-docs pull request #597
Opened 2022-11-23 07:19 UTC by harshilp24

2022-11-23 10:04 UTC, danciaclara requested changes

2022-11-23 10:04 UTC, danciaclara commented on website/docs/reference/appsmith-framework/context-object.md
> +#### fullPath
can we mention about the page id either in fullPath or in pathName?

2022-11-23 11:09 UTC, jnikhila requested changes

2022-11-23 11:09 UTC, jnikhila commented on website/docs/reference/appsmith-framework/context-object.md
> +Query parameters are a predefined set of parameters that are added to the end of a URL. They are URL extensions that help define particular content or actions based on the data being delivered. A URL
```suggestion
Query parameters are a predefined set of parameters that define particular content or actions based on the data being delivered. A URL has all the query parameters appended at the end with a ```?``` as a separator.
```

2022-11-25 07:32 UTC, bharath31 commented on website/docs/reference/appsmith-framework/context-object.md
> +The host property of the URL interface is a string that includes the hostname, and then, a ```:```, followed by the port of the URL(if the [port](/reference/appsmith-framework/context-object#port) is
@danciaclara  `appsmith.URL.host` contains port

2022-11-25 07:36 UTC, jnikhila approved these changes

2022-11-25 07:42 UTC, danciaclara approved these changes

2022-11-25 07:49 UTC, merged