feat: Branding
appsmithorg/appsmith-docs pull request #680
Opened 2022-12-14 06:23 UTC by jsartisan

Adds docs for branding feature

Fixes #674

The docs will be as follows:

- The placement is correct - Keep it under Advanced concepts
- Add new images and annotations as per docs standard
- Add a short video and steps to explain how to upload logo, favicon (based on loom video shared by @dilippitchika) and how it's displayed on Appsmith
- Take a sample logo which could just be a drawing or a sample image placeholder

2022-12-14 06:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/appsmithorg/appsmith-docs?pullRequest=680) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/appsmithorg/appsmith-docs?pullRequest=680) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/appsmithorg/appsmith-docs?pullRequest=680) it.</sub>

2022-12-14 06:57 UTC, jnikhila commented
@jsartisan - Could you please sign and accept the CLA?

2022-12-14 07:15 UTC, jnikhila commented
> Adds docs for branding feature
> 
> Fixes #674

The docs will be as follows:
* The placement is correct - Keep it under Advanced concepts
* Add new images and annotations as per docs standard
* Add a short video and steps to explain how to upload logo, favicon (based on loom video shared by @dilippitchika) and how it's displayed on Appsmith
* Take a sample logo which could just be a drawing or a sample image placeholder

2022-12-15 11:05 UTC, jnikhila requested changes

2022-12-16 08:23 UTC, spark-c commented on website/docs/advanced-concepts/branding.md
> +<!--
Uncommented the tip, was previously commented due to technical difficulty

2022-12-16 11:54 UTC, danciaclara commented on website/docs/advanced-concepts/branding.md
> +
Is this subheading even required?  IMO it looks a bit odd with just one on the right. if there are no other sections on this page, let's avoid this as well. 
<img width="1072" alt="Screenshot 2022-12-16 at 17 20 35" src="https://user-images.githubusercontent.com/32227135/208092224-6a9ffae1-c750-4b56-a48d-4cfd3a410123.png">

2022-12-16 11:56 UTC, danciaclara approved these changes

2022-12-16 11:57 UTC, jnikhila commented on website/docs/advanced-concepts/branding.md
> +
That's fine if there is only one heading. The page runs with lots of text without a heading, and it feels like too much of information. And we are writing about configuring branding here so the heading looks apt.

2022-12-16 11:58 UTC, jnikhila approved these changes

2022-12-16 12:37 UTC, jnikhila commented
@dilippitchika - The PR is ready to be merged. Can we publish it?

2022-12-16 12:42 UTC, merged