fix:Select Widget | Default Value
appsmithorg/appsmith-docs pull request #681
Opened 2022-12-14 06:23 UTC by harshilp24

2022-12-15 10:02 UTC, jnikhila requested changes

2022-12-15 10:02 UTC, jnikhila commented on website/docs/reference/widgets/select.md
> +Please note that this property should be set to match the ```value``` attribute of your desired option from the options property.
Let's not use Please note.
```suggestion
The default selected value should be set to the value of the option from the options property. This value should match the value attribute of the selected option.
```

2022-12-15 10:52 UTC, jnikhila commented on website/docs/reference/widgets/select.md
> +This property allows you to specify a default value that can be selected when the widget is first displayed. This can be useful if you want to pre-populate the widget with a specific value, or if you
Please add an example.

2022-12-15 11:13 UTC, harshilp24 commented on website/docs/reference/widgets/select.md
> +This property allows you to specify a default value that can be selected when the widget is first displayed. This can be useful if you want to pre-populate the widget with a specific value, or if you
done

2022-12-16 11:33 UTC, danciaclara requested changes

2022-12-16 11:33 UTC, danciaclara commented on website/docs/reference/widgets/select.md
> +This property allows you to specify a default value that can be selected when the widget is first displayed. This can be useful if you want to pre-populate the widget with a specific value, or if you
I think the confusion can be avoided by a small modification in the first line

> This property allows you to specify a default value when the widget is first displayed.

2022-12-16 11:33 UTC, danciaclara commented on website/docs/reference/widgets/select.md
> +The default selected value should be set to the value of the option from the options property. This value should match the value attribute of the selected option.
```suggestion
The Default Selected Value should be set to the value of the option from the Options property.
```

these two lines mean the same. Also we can merge this in the first para only.

2022-12-16 11:33 UTC, danciaclara commented on website/docs/reference/widgets/select.md
> +For example, if your options property is an array of objects with a **label** and a **value** property, such as
Wherever the name of the property is mentioned, keep it title case. eg: here Options property

2022-12-19 13:12 UTC, danciaclara approved these changes

2022-12-20 06:38 UTC, jnikhila approved these changes

2022-12-20 06:39 UTC, merged