704 show step arrows
appsmithorg/appsmith-docs pull request #705
Opened 2022-12-26 06:32 UTC by dilippitchika

Fixes #704 

- The new property is to show/hide the increment arrows in widgets
- Added new properties in currency input and input widget
- JS controllable property

2022-12-29 15:08 UTC, danciaclara requested changes
@jnikhila can you also check if this passes the linter test? Thanks :)

2022-12-29 15:08 UTC, danciaclara commented on website/docs/reference/widgets/currency-input.md
> +| **Show step arrows**              | Control's visibility of step arrows. When turned off: The step arrows to increment or decrement the values in the widget will be hidden.
```suggestion
| **Show step arrows**              | Controls visibility of step arrows. Turning this toggle off hides the step arrows to increment or decrement the values in the widget.                                                                        |
```

2022-12-29 15:08 UTC, danciaclara commented on website/docs/reference/widgets/input.md
> +| **Show step arrows**              | Control's visibility of step arrows for a number type input. When turned off: The step arrows to increment or decrement the values in the widget will be hidden.
same as on the suggested change in the Currency input widget. Also, this is valid only for the Number input type right? so we should mention that.

2022-12-30 04:36 UTC, jnikhila commented
@danciaclara - Linter issues are fixed and your suggested changes are merged too.

2023-01-03 11:14 UTC, Pranay105 approved these changes

2023-01-03 11:26 UTC, merged