fix: Email page typo
appsmithorg/appsmith-docs pull request #732
Opened 2023-01-09 12:21 UTC by spark-c

Fixes a typo in a heading on the Email page, and some minor linter fixes.

2023-01-09 16:05 UTC, danciaclara requested changes

2023-01-10 08:16 UTC, spark-c commented on website/docs/getting-started/setup/instance-configuration/email/README.md
> +## Configure using administrator settings
ah good catch, I keep forgetting about the links/anchors/redirects with the headings. reverted.

2023-01-12 08:13 UTC, danciaclara submitted a review, later dismissed

2023-01-19 05:46 UTC, jnikhila approved these changes

2023-01-19 06:09 UTC, merged