Create copyToClipboard.md
appsmithorg/appsmith-docs pull request #75
Opened 2021-01-06 12:51 UTC by hetunandu

2021-01-06 12:54 UTC, Nikhil-Nandagopal commented on function-reference/copyToClipboard.md
> +description: This action is used to copy text to the clipboard
rename action to function

2021-01-06 12:55 UTC, Nikhil-Nandagopal commented on function-reference/copyToClipboard.md
> +Uses the [copy-to-clipboard](https://www.npmjs.com/package/copy-to-clipboard) library
This can be mentioned later as part of the argument list so users know what values the options argument takes

2021-01-06 12:55 UTC, Nikhil-Nandagopal requested changes
@hetunandu minor comments

2021-01-20 10:38 UTC, mohanarpit approved these changes

2021-01-20 10:38 UTC, merged