feat: Adds video "How To Build A Self-Checkout Payment System With The CodeScanner Widget"
appsmithorg/appsmith-docs pull request #814
Opened 2023-02-06 09:16 UTC by megaconfidence

Adds documentation and video guide for "How To Build A Self-Checkout Payment System With The CodeScanner Widget"
Video link https://www.youtube.com/watch?v=Suhefwa5pz0

2023-02-06 09:16 UTC, megaconfidence commented
@Pranay105 @jnikhila please review this 🙏

2023-02-09 10:23 UTC, danciaclara requested changes

2023-02-09 10:23 UTC, danciaclara commented on website/docs/reference/widgets/code-scanner.md
> +<VideoEmbed host="youtube" videoId="Suhefwa5pz0" title="How To Build A Self-Checkout Payment System With The CodeScanner Widget" caption=""/>
@megaconfidence The video appears to be private and is not available
![Uploading Screenshot 2023-02-09 at 15.53.12.png…]()

2023-02-16 13:50 UTC, danciaclara approved these changes

2023-02-16 13:51 UTC, merged