chore: communicate content height to parent iframe using postMessage
appsmithorg/appsmith-docs pull request #912
Opened 2023-02-24 07:51 UTC by sbalaji1192

2023-03-17 15:02 UTC, jnikhila requested changes

2023-03-20 06:20 UTC, sbalaji1192 commented on website/docs/getting-started/setup/upgrade-to-business-edition/upgrade-docker-to-business-edition.mdx
> +<IframeHeight />
Yeah. We want to communicate the docker page document heights so that customer portal sets the height of the iframe accordingly.

2023-03-22 11:32 UTC, sbalaji1192 commented on website/docs/getting-started/setup/upgrade-to-business-edition/upgrade-docker-to-business-edition.mdx
> +<IframeHeight />
@jnikhila - @dipyamanbiswas07 has taken over this issue from me.
@dipyamanbiswas07 can you please give an update here?

2023-03-22 14:16 UTC, jnikhila commented
Closing as no longer needed.

2023-03-22 14:16 UTC, closed without merging