fix: Added note for renaming resources in Git
appsmithorg/appsmith-docs pull request #987
Opened 2023-03-13 09:48 UTC by infinitetrooper

2023-03-13 12:15 UTC, AnaghHegde submitted a review, later dismissed

2023-03-14 05:03 UTC, danciaclara requested changes

2023-03-14 05:03 UTC, danciaclara commented on website/docs/advanced-concepts/version-control-with-git/commit-and-push.md
> +1. Renaming a resource is the same as deleting the old resource and creating a new one in the Git file system. For ex, when you rename a query, you may see `2 queries modified` while trying to commit
```suggestion
1. Renaming a resource is the same as deleting the old resource and creating a new one in the Git file system. For example, when you rename a query, you may see `2 queries modified` while trying to commit; the 2 changes are the old query being deleted and the new one being created.
```

2023-03-14 05:11 UTC, danciaclara approved these changes

2023-03-14 06:00 UTC, merged